apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: feature-flags
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          # ci-managed-image: tag atualizada pelo job update-gitops do CI
          image: 639645545526.dkr.ecr.us-east-1.amazonaws.com/pos2/analytics-service:v1.0.0-dd07ed9
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: AWS_REGION
            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: AWS_SQS_URL
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: AWS_DYNAMODB_TABLE
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
